# Welcome to Basic of Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([1, 2, 3, 4, 5])
myarr

array([1, 2, 3, 4, 5])

In [3]:
print(myarr)

[1 2 3 4 5]


# Printing Element by Indexing!

In [4]:
myarr[2]

3

In [5]:
myarr[0]

1

In [6]:
print(myarr[4])

5


In [7]:
myarr[4]

5

In [8]:
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr

array([1, 2, 3, 4, 5], dtype=int64)

In [9]:
print(myarr)

[1 2 3 4 5]


In [10]:
myarr1 = np.array([[1, 2, 3, 4, 5]])
myarr1[0, 2]

3

In [11]:
print(myarr1[0, 3])

4


In [12]:
myarr1.shape

(1, 5)

In [13]:
myarr1[0, 2] = 10

In [14]:
myarr1

array([[ 1,  2, 10,  4,  5]])

In [15]:
listArr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(listArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
listArr.shape

(3, 4)

In [17]:
listArr.size

12

In [18]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
zeros.dtype

dtype('float64')

In [21]:
range = np.arange(10)
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
print(range)

[0 1 2 3 4 5 6 7 8 9]


# Mathematical tools use here

In [23]:
IdMatrix = np.identity(45)

In [24]:
IdMatrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
print(IdMatrix)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [26]:
IdMatrix.shape

(45, 45)

In [27]:
IdMatrix.size

2025

# Important Point

In [28]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
ar.sum(axis=0)

array([12, 15, 18])

In [31]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [32]:
 ar.T            #Transpose of Array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
ar.flat

In [34]:
for item in range:
    print(item)

0
1
2
3
4
5
6
7
8
9


In [35]:
ar.ndim

2

In [36]:
ar.size

9

In [37]:
ar.nbytes

36

In [41]:
oneDArray = np.array([6, 2, 40, 4, 200, 3])

In [42]:
oneDArray.argmax()

4

In [43]:
oneDArray.argmin()

1

In [45]:
oneDArray.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [46]:
print(oneDArray.argsort())

[0 1 2 3 4 5]


In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ar.argmin()

0

In [49]:
ar.argmax()

8

In [51]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [55]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [56]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [57]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [58]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [59]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)